version: '3.7'

services:
  mysql:
    container_name: dealership-mysql
    image: inf21dw2g02/rep1:dealership-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # schema?
    networks:
      - dealership-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: dealership-app
    image: inf21dw2g02/rep2:dealership-app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - dealership-network

networks:
  dealership-network: